import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Layout from '@/components/Common/Layout'
import AnimatedText from '@/animations/AnimatedText'
import profilePic from "../../public/images/profile/ProfileIcon2.png";
import Link from 'next/link'
import { LinkArrow } from '@/components/Common/Icons'
import ConnectWithMe from '@/components/Home/ConnectWithMe'
import controller from "../../public/images/home/controller.png";

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>

        <title>Gabi Anderson</title>

        <meta name="description" content="Generated by create next app" />
        
      </Head>
      <main className='flex items-center text-dark w-full min-h-screen dark:text-light'>
        
        <Layout className='pt-0'>
          <div className='flex items-center justify-between w-full'>
            <div className='w-1/2'>

              <Image src={profilePic} alt="ProfilePhoto" className='w-[70%] h-auto mx-auto'
              priority
              sizes="(max-width: 768px) 100vs, (max-width: 1200px) 50vw, 50vw" />
            
            </div>
            
            <div className='w-1/2 flex flex-col item-center self-center'>
            <h1 className="text-6xl text-left">
              <span className="text-primary">Gabriela </span> Anderson
            </h1>
              <AnimatedText text="Player to Creator: Coding from Pixels to Play." className='!text-3xl !text-left mt-4 text-dark/50 dark:text-light/50' />
              
              <p className='my-4 text-base font-medium'>
                As a recent computer science graduate with a specialization in video game
                development and a flair for creative code, I&apos;m on a mission to bring captivating
                gaming experiences to life. Explore my projects that fuse art, technology, and
                problem-solving, unleashing the power of imagination in the gaming world.
              </p>
              
              <div className='flex items-center self-start mt-2'>
                <Link href="/GabrielaAnderson_Resume.pdf" target={"_blank"}
                  className='flex items-center bg-dark text-light p-2.5 px-6
                  rounded-lg text-lg font-semibold hover:bg-light hover:text-dark
                  border-2 border-solid border-transparent hover:border-primary
                  dark:bg-light dark:text-dark dark:hover:bg-dark dark:hover:text-light'
                  download={true}
                >Resume
                  <LinkArrow className={"w-6 ml-1"} /></Link>
                
                <Link href="mailto:gabi84095@gmail.com" target={"_blank"}
                className='ml-4 text-lg font-medium capitilize text-dark border-b-2 border-b-primary hover:border-b-accentgreen dark:text-light'>Contact</Link>
              </div>
            </div>
          </div>
        </Layout>

        <ConnectWithMe />
        <div className='absolute right-16 bottom-16 inline-block w-24'>
          <Image src={controller} alt="GabiAnderson" className='w-full h-auto' style={{ transform: 'scale(2)' }} />
        </div>
      </main>
    </>
  )
}
